const Strings = {
    VAN_BAN_DEN: 'Văn bản đến',
    VAN_BAN_DI: 'Văn bản đi',
    TO_TRINH: 'Tờ trình',
    VAN_BAN_NOI_BO: 'Văn bản nội bộ',
    GIAO_VIEC: 'Giao việc',
    HO_SO_CONG_VIEC: 'Hồ sơ công việc',
    LICH_LANH_DAO: 'Lịch lãnh đạo',
    LICH_CONG_TAC: 'Lịch công tác',
    LICH_XE: 'Lịch xe',
    PHONG_HOP: 'Phòng họp',
    THONG_TIN_VAN_BAN: 'Thông tin văn bản',
    LICH_SU_XU_LY: 'Lịch sử xử lý',
    VAN_BAN_GOC_VB_LIEN_QUAN: 'Văn bản gốc/ Văn bản liên quan',
    HO_SO: 'Hồ sơ',
    VBD_DA_VAO_SO: 'Đã vào sổ',
    VBD_THU_KY_TRA_LAI: 'Thư ký trả lại',
    VBD_MOI_HOP: 'Mời họp',
    VBD_PHIEU_TRINH: 'Phiếu trình',
    VDB_TRINH_LANH_DAO: 'Trình lãnh đạo',
    VBD_PHAI_THEO_DOI: 'Phải theo dõi',
    VBD_CAN_XU_LY: 'Cần xử lý',
    VBD_DANG_TRINH_LD_CQ: 'Đang trình LĐ \n cơ quan',
    TT_DV_TRINH_MOI: 'ĐV trình mới',
    TT_LD_COQUAN_TRA: 'LĐ cơ quan trả',
    TT_XIN_Y_KIEN: 'Xin ý kiến',
    TT_LD_KHAC_CHUYEN_SANG: 'LĐ khác \n chuyển sang',
    TT_CAN_THEO_DOI: 'Cần theo dõi',
    TT_CAN_PHE_DUYET: 'Cần phê duyệt',
    TT_TO_TRINH_CAN_XU_LY: 'Cần xử lý',
    TT_DA_CAP_SO: 'Đã cấp số',
    TT_TO_TRINH_CQ_TRA_LAI: 'Cơ quan trả lại',
    VBDI_CAN_XU_LY: 'Cần xử lý',
    VBDI_CHO_CAP_SO: 'Chờ cấp số',
    VBDI_CAN_PHAT_HANH: 'Cần phát hành',
    VBDI_XEM_CHI_TIET: 'Thông tin văn bản',
    HOSO_DANG_MO: 'Đang mở',
    HOSO_DA_NOP_LUU: 'Đã nộp lưu',
    THONG_TIN_HO_SO: 'Thông tin hồ sơ',
    VAN_BAN_TRONG_HO_SO: 'Văn bản trong hồ sơ',
    LICH_SU_HO_SO: 'Lịch sử hồ sơ',
    DETAIL_CAR: 'DETAIL_CAR',
    PHIEU_GIAO_VIEC: 'Phiếu giao việc',
    VAN_BAN_DEN_PHIEU_TRINH: 'Văn bản đến phiếu trình',
    VAN_BAN_DEN_MOI_HOP: 'Văn bản đến mời họp',
    VAN_BAN_DEN_TRINH_LANH_DAO: 'Phiếu trình đang trình lãnh đạo',
    VAN_BAN_DEN_PHAI_THEO_DOI: 'Văn bản đến phải theo dõi',
    CHUYEN_VTDV: 'Chuyển văn thư đơn vị thành công',
    THONG_BAO: 'Thông báo',
    NHAP_Y_KIEN: 'Vui lòng nhập ý kiến xử lý',
    GHI_THANH_CONG: "Ghi dữ liệu thành công",
    DUNG_VAN_BAN: "Dừng văn bản thành công",
    CHUYEN_THAT_BAI: 'Chuyển thất bại',
    KET_THUC_VAN_BAN: 'Đã kết thúc văn bản',
    CHUYEN_THANH_CONG: 'Chuyển thành công',
    DANG_NHAP_LOI: 'Có lỗi trong quá trình đăng nhập',
    TRINH_MOI_MOI_HOP: 'Trình mới - Mời họp',
    TRINH_MOI_PHIEU_TRINH: 'Trình mới - Phiếu trình',
    DANG_TRINH_MOI_HOP: 'Đang trình LĐ - Mời họp',
    DANG_TRINH_PHIEU_TRINH: 'Đang trình LĐ - Phiếu trình',
    LD_YKIEN_MOI_HOP: 'LĐ ý kiến - Mời họp',
    LD_YKIEN_PHIEU_TRINH: 'LĐ ý kiến - Phiếu trình',
  };
  
  export default Strings;
  