import CONFIG from "../apis/config";

const EdocIcon = {
  //logo
  logo: CONFIG.unit === 'BTC' ? require('../assets/img/login/logo.png') : CONFIG.unit === 'HQ' ? require('../assets/img/login/haiquan.jpg') : require('../assets/img/login/logo1.png'),
  // logo: require('assets/img/login/logo1.png'),
  splash: require('../assets/img/common/splash.png'),
  //finger
  fingerPrint: require('../assets/img/login/finger_print.png'),
  faceID: require('../assets/img/login/faceid.png'),
  //calendar
  homeCalendar: require('../assets/img/calendar/home_calendar.png'),
  leaderMinistry: require('../assets/img/calendar/leader_ministry.png'),
  leaderUnit: require('../assets/img/calendar/leader_unit.png'),
  arrowRight: require('../assets/img/calendar/arrowRight.png'),
  arrowLeft: require('../assets/img/calendar/arrowLeft.png'),
  calendar_new: require('../assets/img/calendar/calendar.png'),
  dropdown: require('../assets/img/calendar/dropdown.png'),
  nextMonth: require('../assets/img/calendar/nextMonth.png'),
  preMonth: require('../assets/img/calendar/preMonth.png'),
  showEye: require('../assets/img/calendar/show_eye.png'),
  hideEye: require('../assets/img/calendar/hide_eye.png'),
  icDoc: require('../assets/img/calendar/ic_doc.png'),
  icPdf: require('../assets/img/calendar/ic_pdf.png'),
  icXls: require('../assets/img/calendar/ic_xls.png'),

  icDelete2: require('../assets/img/common/ic_delete1.png'),
  icFilter: require('../assets/img/common/filter.png'),
  arrowdown: require('../assets/img/common/arrow_down.png'),
  arrowup: require('../assets/img/common/arrow_up.png'),
  //home
  bgHome: require('../assets/img/home/bgHome.png'),
  icSearchAdvance: require('../assets/img/home/ic_search_advance.png'),
  icSearch: require('../assets/img/home/ic_search.png'),
  icHome: require('../assets/img/home/home.png'),
  icNotification: require('../assets/img/home/notification.png'),
  icSetting: require('../assets/img/home/setting.png'),
  //dashboard
  icIcomingText: require('../assets/img/home/ic_vb_den.png'),
  icGoText: require('../assets/img/home/ic_vb_di.png'),
  icReport: require('../assets/img/home/ic_to_trinh.png'),
  icInternalText: require('../assets/img/home/ic_vb_noi_bo.png'),
  icAssign: require('../assets/img/home/ic_giao_viec.png'),
  icJobProfile: require('../assets/img/home/ic_hs_cong_viec.png'),
  icLeaderShipCalendar: require('../assets/img/home/ic_lich_lanh_dao.png'),
  icSeeMore: require('../assets/img/home/ic_xem_them.png'),
  icSearchWhite: require('../assets/img/common/ic_search.png'),
  icCalendarCar: require('../assets/img/home/ic_calender_car.png'),
  icMettingRoom: require('../assets/img/home/ic_metting_room.png'),
  //incoming documents
  icWarning: require('../assets/img/common/ic_warning.png'),
  // icFolder: require('assets/img/common/icon_file.png'),
  icFolder: require('../assets/img/common/ic_folder.png'),
  // icFolder: require('assets/img/common/icon_file.png'),
  icDelete: require('../assets/img/common/ic_delete.png'),
  //setting
  icExit: require('../assets/img/setting/ic_exit.png'),
  icFavoriteFunc: require('../assets/img/setting/ic_favorite_func.png'),
  icHomeSetting: require('../assets/img/setting/ic_home_setting.png'),
  icMyGov: require('../assets/img/setting/ic_my_gov.png'),
  icRoles: require('../assets/img/setting/roles.png'),
  icPerson: require('../assets/img/setting/ic_person.png'),
  icVersion: require('../assets/img/setting/info-circle.png'),
  icUserScret: require('../assets/img/setting/user-secret.png'),
  icCheck: require('../assets/img/setting/ic_check.png'),
  icNotCheck: require('../assets/img/setting/ic_not_check.png'),
  icMenu: require('../assets/img/setting/ic_menu.png'),
  icCircleMinus: require('../assets/img/setting/ic_circle_minus.png'),
  icCirclePlus: require('../assets/img/setting/ic_circle_plus.png'),
  //common
  icCalendarDropdown: require('../assets/img/common/ic_calender_dropdown.png'),
  icColose: require('../assets/img/common/ic_close.png'),
  icAttach: require('../assets/img/common/ic_attach.png'),
  icExpand: require('../assets/img/common/ic_expand.png'),
  icCheckbox: require('../assets/img/common/ic_checkbox.png'),
  icCheckboxChecked: require('../assets/img/common/ic_checkbox_checked.png'),
  icSign: require('../assets/img/common/ic_signature.png'),
  icComment: require('../assets/img/common/ic_comment.png'),
  icList: require('../assets/img/common/list-solid.png'),
  //notification
  icCircleBlue: require('../assets/img/notification/ic_circle_blue.png'),
  ic_bell: require('../assets/img/notification/bell-solid.png'),
  ic_history: require('../assets/img/setting/ic_history.png'),
  ic_arr_down: require('../assets/img/calendar/ic_arr_down.png'),
  ic_arr_up: require('../assets/img/calendar/ic_arr_up.png'),
  ic_document: require('../assets/img/calendar/ic_document.png'),
  ic_file_sharing: require('../assets/img/calendar/ic_file_sharing.png'),
  ic_translate: require('../assets/img/calendar/ic_translate.png'),
  ic_more: require('../assets/img/calendar/ic_more.png'),
  img_btc: require('../assets/img/calendar/img_btc.png'),
};

export default EdocIcon;
