class RouteName {
    //Auth
    LOGIN: string = 'LOGIN';
    REGISTER: string = 'REGISTER';
    INTRO: string = 'INTRO';
    DETAIL_INTRO: string = 'DETAIL_INTRO';
    LIBRARY_SCREEN: string = 'LIBRARY_SCREEN';
    //trang chủ
    HOME: string = 'HOME';
    TABNAVIGATION: string = 'TABNAVIGATION';
    //lịch
    // LEADER_SHIP_CALENDAR: string = 'LEADER_SHIP_CALENDAR';
    //văn bản đến
    INCOMING_DOCUMENT_MAIN: string = 'INCOMING_DOCUMENT_MAIN';
    INCOMING_DOCUMENT_DETAIL: string = 'INCOMING_DOCUMENT_DETAIL';
    INCOMING_DOCUMENT_DETAIL_SEARCH: string = 'INCOMING_DOCUMENT_DETAIL_SEARCH';
    INCOMING_DOCUMENT_DAVAOSO: string = 'INCOMING_DOCUMENT_DAVAOSO';
    INCOMING_DOCUMENT_DETAIL_HISTORY: string = 'INCOMING_DOCUMENT_DETAIL_HISTORY';
    INCOMING_DOCUMENT_THUKYTRALAI: string = 'INCOMING_DOCUMENT_THUKYTRALAI';
    INCOMING_DOCUMENT_MOIHOP: string = 'INCOMING_DOCUMENT_MOIHOP';
    INCOMING_DOCUMENT_PHIEUTRINH: string = 'INCOMING_DOCUMENT_PHIEUTRINH';
    INCOMING_DOCUMENT_TRINHLANHDAO: string = 'INCOMING_DOCUMENT_TRINHLANHDAO';
    INCOMING_DOCUMENT_PHAITHEODOI: string = 'INCOMING_DOCUMENT_PHAITHEODOI';
    INCOMING_DOCUMENT_CANXULY: string = 'INCOMING_DOCUMENT_CANXULY';
    INCOMING_DOCUMENT_TRINHLANHDAOCOQUAN: string = 'INCOMING_DOCUMENT_TRINHLANHDAOCOQUAN';
    INCOMING_DOCUMENT_RETURN: string = 'INCOMING_DOCUMENT_TRINHLANHDAOCOQUAN';
    INCOMING_TRANFER_LEADER: string = 'INCOMING_TRANFER_LEADER';
    INCOMING_TRANFER_UNIT: string = 'INCOMING_TRANFER_UNIT';
    INCOMING_TRANFER_ADD_UNIT: string = 'INCOMING_TRANFER_ADD_UNIT';
    INCOMING_TRANFER_ADD_BO: string = 'INCOMING_TRANFER_ADD_BO';
    INCOMING_TRINH_LANH_DAO_DON_VI: string = 'INCOMING_TRINH_LANH_DAO_DON_VI';
    INCOMING_CHUYEN_XU_LY_DON_VI: string = 'INCOMING_CHUYEN_XU_LY_DON_VI';
    INCOMING_CHUYEN_XU_LY_CHUYEN_VIEN: string = 'INCOMING_CHUYEN_XU_LY_CHUYEN_VIEN';
    INCOMING_CHUYEN_XU_LY_CHUYEN_VIEN_DV: string = 'INCOMING_CHUYEN_XU_LY_CHUYEN_VIEN_DV';
    INCOMING_THU_HOI_VAI_TRO: string = 'INCOMING_THU_HOI_VAI_TRO';
    //tìm kiếm
    SEARCH: string = 'SEARCH';
    ADVANCE_SEARCH: string = 'ADVANCE_SEARCH';
    DANH_SACH_TIM_KIEM: string = 'DANH_SACH_TIM_KIEM';
    //cài đặt
    SETTING: string = 'SETTING';
    CUSTOM_FAVORITE_FUNCTION: string = 'CUSTOM_FAVORITE_FUNCTION';
    PERSONAL_INFOMATION: string = 'PERSONAL_INFOMATION';
    PRIVACY_INFOMATION: string = 'PRIVACY_INFOMATION';
    //thông báo
    NOTIFICATION_LIST: string = 'NOTIFICATION_LIST';
    //tờ trình
    PRESENTATION_MAIN: string = 'PRESENTATION_MAIN';
    PRESENTATION_DV_TRINH_MOI: string = 'PRESENTATION_DV_TRINH_MOI';
    PRESENTATION_LD_COQUAN_TRA: string = 'PRESENTATION_LD_COQUAN_TRA';
    PRESENTATION_XIN_Y_KIEN: string = 'PRESENTATION_XIN_Y_KIEN';
    PRESENTATION_LD_KHAC_CHUYEN_SANG: string = 'PRESENTATION_LD_KHAC_CHUYEN_SANG';
    PRESENTATION_CAN_THEO_DOI: string = 'PRESENTATION_CAN_THEO_DOI';
    PRESENTATION_CAN_PHE_DUYET: string = 'PRESENTATION_CAN_PHE_DUYET';
    PRESENTATION_CAN_XU_LY: string = 'PRESENTATION_CAN_XU_LY';
    PRESENTATION_DA_CAP_SO: string = 'PRESENTATION_DA_CAP_SO';
    PRESENTATION_CQ_TRA_LAI: string = 'PRESENTATION_CQ_TRA_LAI';
    PRESENTATION_DETAIL: string = 'PRESENTATION_DETAIL';
    PRESENTATION_RETURN: string = 'PRESENTATION_RETURN';
    PRESENTATION_SEND: string = 'PRESENTATION_SEND';
    PRESENTATION_SEND_YKIEN: string = 'PRESENTATION_SEND_YKIEN';
    PRESENTATION_YKIEN_SEND: string = 'PRESENTATION_YKIEN_SEND';
    PRESENTATION_DETAIL_PROCESS: string = 'PRESENTATION_DETAIL_PROCESS';
    PRESENTATION_DONG_TRINH: string = 'PRESENTATION_DONG_TRINH';
  
    //văn bản đi
    GO_TEXT_MAIN: string = 'GO_TEXT_MAIN';
    GO_TEXT_CAN_XU_LY: string = 'GO_TEXT_CAN_XU_LY';
    GO_TEXT_CAN_PHAT_HANH: string = 'GO_TEXT_CAN_PHAT_HANH';
    GO_TEXT_DETAIL: string = 'GO_TEXT_DETAIL';
    TRA_LAI_VANBAN_DI: string = 'TRA_LAI_VANBAN_DI';
    CHUYEN_VANBAN_DI: string = 'CHUYEN_VANBAN_DI';
    CHI_TIET_LICH_SU_XU_LY: string = 'CHI_TIET_LICH_SU_XU_LY';
    //văn bản nội bộ
    INTERNAL_TEXT_CAN_XU_LY: string = 'INTERNAL_TEXT_CAN_XU_LY';
    INTERNAL_TEXT_DETAIL: string = 'INTERNAL_TEXT_DETAIL';
    //Hồ sơ giao việc
    JOB_PROFILE_MAIN: string = 'JOB_PROFILE_MAIN';
    JOB_PROFILE_DETAIL: string = 'JOB_PROFILE_DETAIL';
    JOB_PROFILE_DETAIL_CAN_THEO_GIOI: string = 'JOB_PROFILE_DETAIL_CAN_THEO_GIOI';
    JOB_PROFILE_DANG_MO: string = 'JOB_PROFILE_DANG_MO';
    JOB_PROFILE_DA_NOP_LUU: string = 'JOB_PROFILE_DA_NOP_LUU';
    CHUYEN_XU_LY_PHIEU_GIAO_VIEC: string = 'CHUYEN_XU_LY_PHIEU_GIAO_VIEC';
    CAP_NHAT_KQ_PHIEU_GIAO_VIEC: string = 'CAP_NHAT_KQ_PHIEU_GIAO_VIEC';
    PHIEU_GIAO_VIEC: string = 'PHIEU_GIAO_VIEC';
    DANH_GIA_GIAO_VIEC: string = 'DANH_GIA_GIAO_VIEC';
    //Lịch xe
    CAR_LIST_CALENDAR: string = 'CAR_LIST_CALENDAR';
    CAR_DETAIL: string = 'CAR_DETAIL';
    CAR_CALENDAR_ACTIVE: string = 'CAR_CALENDAR_ACTIVE';
    CAR_CALENDAR_MONTH: string = 'CAR_CALENDAR_MONTH';
    //Hồ sơ công việc
    JOBINFO_MAIN: string = 'JOBINFO_MAIN';
    JOBINFO_NEED_HANDLE: string = 'JOBINFO_NEED_HANDLE';
    JOBINFO_DETAIL: string = 'JOBINFO_DETAIL';
    CHUYEN_LANH_DAO: string = 'CHUYEN_LANH_DAO';
    JOBINFO_MAPPING_DOCUMENT: string = 'JOBINFO_MAPPING_DOCUMENT';
    JOBINFO_SEARCH_DOCUMENT: string = 'JOBINFO_SEARCH_DOCUMENT';
    JOBINFO_LIST_DOCUMENT: string = 'JOBINFO_LIST_DOCUMENT';
    //Lịch phòng
    ROOM_MEETING_CALENDAR: string = 'ROOM_MEETING_CALENDAR';
    ROOM_MEETING_DETAIL: string = 'ROOM_MEETING_DETAIL';
    ROOM_MEETING_ACTIVE: string = 'ROOM_MEETING_ACTIVE';
    ROOM_MEETING_CALENDAR_MONTH: string = 'ROOM_MEETING_CALENDAR_MONTH';
    HISTORY_FILE: string = 'HISTORY_FILE';
    //Lịch họp
    PERSONAL_CALENDAR_USER: string = 'PERSONAL_CALENDAR_USER';
    PERSONAL_CALENDAR_DETAIL: string = 'PERSONAL_CALENDAR_DETAIL';
    PERSONAL_CALENDAR_WEEK: string = 'PERSONAL_CALENDAR_WEEK';
    PERSONAL_CALENDAR_MONTH: string = 'PERSONAL_CALENDAR_MONTH';
    PERSONAL_CALENDAR: string = 'PERSONAL_CALENDAR';
    MINISTRY_LEADER_CALENDAR: string = 'MINISTRY_LEADER_CALENDAR';
    UNIT_LEADER_CALENDAR: string = 'UNIT_LEADER_CALENDAR';
    VIEW_XLSX: string = 'VIEW_XLSX';
    DOCUMENT_INFO_SCREEN: string = 'DOCUMENT_INFO_SCREEN';
  }
  export default new RouteName();
  