import CONFIG from "../apis/config";

export const Message = {
    //LOGIN
    Default: CONFIG.unit == 'BTC' ? 'Chương trình Quản lý văn bản và điều hành' : CONFIG.unit=='HQ' ? 'Hệ thống Quản lý văn bản Hải Quan' : 'Hệ thống Quản lý văn bản EdocTC',
    // Default: 'EdocTC',
    DefaultHome: 'Chương trình Quản lý văn bản và điều hành',

    //Action
    CHUYEN_XU_LY: 'Chuyển xử lý',
    CHUYEN_DONG_TRINH: 'Chuyển đồng trình',
    CAP_SO: 'Cấp số',
    GHI_LAI: 'Ghi lại',
    TRA_LAI: 'Trả lại',
    CHUYEN_LD_BO: 'Chuyển Lãnh đạo Bộ',
    CHON_LANH_DAO: 'Bạn chưa chọn lãnh đạo!',
    CHUYEN_VT: 'Chuyển văn thư',
    CHUYEN_VTDV: 'Chuyển VT đơn vị',
    CHUYEN_THAM_DINH: 'Chuyển thẩm định',
    TRA_LAI_DV: 'Trả lại đơn vị',
    TRA_LAI_TK: 'Trả lại thư ký',
    TRINH_LD_PHUTRACH: 'Trình Lãnh đạo phụ trách',
    TRINH_LD_KHAC: 'Trình Lãnh đạo khác',
    PHE_DUYET: 'Phê duyệt',
    GIAI_QUYET_XONG: 'Giải quyết xong',
    YEU_CAU_HOAN_THIEN: 'Yêu cầu hoàn thiện',
    CHUYEN_XIN_YKIEN: 'Chuyển xin ý kiến',
    ERROR_DATA: 'Vui lòng nhập đầy đủ dữ liệu!',
    REGISTER_SUCCESS: 'Đăng ký thành công!',
    DA_CO_LOI_XAY_RA: 'Đã có lỗi xảy ra!',

    //Notification
    THONG_BAO: 'Thông báo',
    TRINH_LD_SUCCESS: 'Trình Lãnh đạo thành công!',
    TRINH_LD_FALSE: 'Trình Lãnh đạo thất bại!',
    TRINH_LDVP_SUCCESS: 'Trình Lãnh đạo văn phòng thành công!',
    TRINH_LDVP_FALSE: 'Trình Lãnh đạo văn phòng thất bại!',
    HAN_XU_LY_INVALID: 'Hạn xử lý phải lớn hơn hoặc bằng ngày hiện tại!',
    HAN_XU_LY_BLANK: 'Anh/chị chưa chọn hạn xử lý!',
    CHU_TRI_BLANK: 'Anh/chị chưa chọn chủ trì!',
    CHUYEN_LD_SUCCESS: 'Chuyển Lãnh đạo thành công!',
    CHUYEN_LD_FALSE: 'Chuyển Lãnh đạo thất bại!',
    CHUYEN_LDVP_SUCCESS: 'Chuyển Lãnh đạo văn phòng thành công!',
    CHUYEN_LDVP_FALSE: 'Chuyển Lãnh đạo văn phòng thất bại!',
    CHUYEN_XU_LY_SUCCESS: 'Chuyển xử lý thành công!',
    CHUYEN_VANBAN_SUCCESS: 'Chuyển văn bản thành công!',
    CHUYEN_VANBAN_FALSE: 'Chuyển văn bản thất bại!',
    CHUYEN_VANTHU_SUCCESS: 'Chuyển văn thư thành công!',
    CHUYEN_VANTHU_FALSE: 'Chuyển văn thư thất bại!',
    CHUYEN_TOTRINH_SUCCESS: 'Chuyển tờ trình thành công!',
    CHUYEN_TOTRINH_FALSE: 'Chuyển tờ trình thất bại!',
    CHUYEN_XIN_Y_KIEN_SUCCESS: 'Chuyển xin ý kiến thành công!',
    CHUYEN_XIN_Y_KIEN_FALSE: 'Chuyển xin ý kiến thất bại!',
    OPINION_BLANK: 'Vui lòng nhập ý kiến!',
    OPINION_CONSL_BLANK: 'Vui lòng nhập ý kiến tham mưu!',
    GHI_DULIEU_SUCCESS: 'Ghi dữ liệu thành công!',
    GHI_DULIEU_FALSE: 'Ghi dữ liệu thất bại!',
    PHE_DUYET_SUCCESS: 'Phê duyệt thành công!',
    PHE_DUYET_FALSE: 'Phê duyệt thất bại!',
    GIAI_QUYET_SUCCESS: 'Giải quyết thành công!',
    GIAI_QUYET_FALSE: 'Giải quyết thất bại!',
    CAP_SO_SUCCESS: 'Cấp số thành công!',
    CAP_SO_FALSE: 'Cấp số thất bại!',
    TO_TRINH_DA_CAPSO: 'Tờ trình đã được cấp số!',
    TRA_LAI_DV_SUCCESS: 'Trả lại đơn vị thành công!',
    TRA_LAI_DV_FALSE: 'Trả lại đơn vị thất bại!',
    TRA_LAI_THUKY_SUCCESS: 'Trả lại thư ký thành công!',
    TRA_LAI_THUKY_FALSE: 'Trả lại thư ký thất bại!',
    TRA_LAI_VANBAN_SUCCESS: 'Trả lại văn bản thành công!',
    TRA_LAI_VANBAN_FALSE: 'Trả lại văn bản thất bại!',
    TRA_LAI_TOTRINH_SUCCESS: 'Trả lại tờ trình thành công!',
    TRA_LAI_TOTRINH_FALSE: 'Trả lại tờ trình thất bại!',
    USER_RETURN_BLANK: "Chưa chọn người trả lại!",
    USER_RETURN_THU_HOI: "Chưa chọn người thu hồi!",
    USER_TRANSFER_BLANK: 'Vui lòng chọn người chuyển!',
    USER_INVALID: 'Vui lòng chọn Lãnh đạo bộ khác Trình lãnh đạo!',
    PICKER_TYPE_DOC: 'Vui lòng chọn loại văn bản',
    INVALID_CAP_SO: 'Vui lòng cấp số tờ trình!',
    INVALID_PICKER_CT_PP: 'Vui lòng chọn chủ trì hoặc phối hợp!',
    NOP_LUU_TRU_SUCCESS: 'Nộp lưu trữ thành công!',
    NOP_LUU_TRU_FALSE: 'Nộp lưu trữ thất bại!',

};
